version: "3.2"
services:
  cache:
    container_name: cache
    image: memcached:latest
    ports:
      - "11211:11211"
    entrypoint:
      - memcached
      - -m 64
  rabbit:
    container_name: rabbit
    image: rabbitmq:latest
    ports:
      - "5672:5672"
